version: "3"

services:
  test_runner:
    build: .
    image: pytest_runner
    container_name: pytest_runner_works
    environment:
      - ENV=dev
    volumes:
      - .:/tests_project/

# docker-compose up --build

# docker
# 1) docker pull python
# 2) docker build -t pytest_runner .
# docker run --rm --mount type=bind,src=C:\Users\user\PycharmProjects\Python_API,target=/tests_project/ pytest_runner
# --rm удаление контейнера
#
# allure
# python -m pytest --alluredir=framework/tests/test_result/ framework/tests/test_user_auth.py
# allure serve framework/tests/test_result/
# https://docs.qameta.io/allure/
